#!/bin/bash
install_java8() {
    codename=$(_os_codename)
    distribution=$(_os_distro)
    if [[ $distribution == "ubuntu" ]]; then
        apt_install openjdk-17-jdk-headless
    elif [[ $distribution == "debian" ]]; then
        case $codename in
            *)
                echo_progress_start "Adding adoptopenjdk repository"
                curl -s https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor > /usr/share/keyrings/adoptopenjdk-archive-keyring.gpg 2>> "${log}"
                echo "deb [signed-by=/usr/share/keyrings/adoptopenjdk-archive-keyring.gpg] https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" > /etc/apt/sources.list.d/adoptium.list
                echo_progress_done "adoptopenjdk repos enabled"
                apt_update
                apt_install openjdk-17-jdk-headless
                ;;
        esac
    fi
}
